### ISSUE TITLE
Unable to resume activity {com.totemsoft.screenlookcount/com.totemsoft.screenlookcount.ActivityMain}: de.greenrobot.dao.DaoException: Expected unique result, but count was 2

### ISSUE THREAD

**Issue by vanniktech** [lomza/screenlookcount#2]
This is the stracktrace:

```
java.lang.RuntimeException: Unable to resume activity {com.totemsoft.screenlookcount/com.totemsoft.screenlookcount.ActivityMain}: de.greenrobot.dao.DaoException: Expected unique result, but count was 2
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
 at android.app.ActivityThread.-wrap11(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6494)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: de.greenrobot.dao.DaoException: Expected unique result, but count was 2
 at de.greenrobot.dao.AbstractDao.loadUnique(Unknown Source:39)
 at de.greenrobot.dao.AbstractDao.loadUniqueAndCloseCursor(Unknown Source:0)
 at de.greenrobot.dao.InternalQueryDaoAccess.b(Unknown Source:2)
 at de.greenrobot.dao.query.Query.d(Unknown Source:19)
 at de.greenrobot.dao.query.QueryBuilder.b(Unknown Source:4)
 at com.totemsoft.screenlookcount.db.LookCountDbManager.getDayLookByDate(Unknown Source:34)
 at com.totemsoft.screenlookcount.fragment.FragmentMain.setCountersValues(Unknown Source:11)
 at com.totemsoft.screenlookcount.fragment.FragmentMain.onResume(Unknown Source:3)
 at android.support.v4.app.Fragment.performResume(Unknown Source:20)
 at android.support.v4.app.FragmentManagerImpl.a(Unknown Source:689)
 at android.support.v4.app.FragmentManagerImpl.a(Unknown Source:52)
 at android.support.v4.app.FragmentManagerImpl.a(Unknown Source:1)
 at android.support.v4.app.FragmentManagerImpl.o(Unknown Source:4)
 at android.support.v4.app.FragmentController.i(Unknown Source:4)
 at android.support.v4.app.FragmentActivity.onResumeFragments(Unknown Source:2)
 at android.support.v4.app.FragmentActivity.onPostResume(Unknown Source:9)
 at android.support.v7.app.AppCompatActivity.onPostResume(Unknown Source:0)
 at android.app.Activity.performResume(Activity.java:7131)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
 ... 10 more
```

Using version 1.1 with my Pixel XL (1st generation).

**Comment by vanniktech** [comment]
Ended up uninstalling the app as this will be backed by Android P natively.

**Comment by antoninatkachuk** [comment]
@vanniktech , I will make an update to the app soon. I have completely re-written it and instead greenDAO there's Room, where this bug is not occurring. And yes, I've heard about Android P's statistics screen. Of course it's your choice to use it :) I will check it out too when it's released.
